exclude: 'docs|node_modules|migrations|.git'
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    # add supported hooks https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

  - repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
      exclude: ^.*\b(migrations)\b.*$

    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
