repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      # See bug: https://github.com/psf/black/issues/2964
      # If possible, run rev: 22.3.0 to obviate the need for pinning click
      # additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
#  - repo: https://github.com/pre-commit/mirrors-eslint
#  rev: v8.3.0
#  hooks:
#    - id: eslint
