# Generated by Django 3.2.9 on 2021-11-24 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="owner",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"),
            preserve_default=False,
        ),
    ]
