# Generated by Django 4.0.6 on 2022-07-06 01:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_age_customuser_bio_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
    ]
